CREATE DATABASE DB_ENSINA_DEV;
USE DB_ENSINA_DEV;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_USUARIO VARCHAR (80) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR (255) NOT NULL,
    NOME_USUARIO VARCHAR (20) NOT NULL UNIQUE,
    IMAGEM_USUARIO VARCHAR (255) UNIQUE,	# caminho da imagem
    TIPO_USUARIO CHAR (1) NOT NULL,		# A = adm; E = estudante
    PRIMARY KEY (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_CONTATO (
	ID_CONTATO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_CONTATO VARCHAR(80) NOT NULL UNIQUE,
    TEXTO_CONTATO TEXT NOT NULL,
    DATA_CONTATO DATETIME NOT NULL,
    RESPONDIDO_CONTATO TINYINT NOT NULL,
    PRIMARY KEY (ID_CONTATO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TEMA (
    ID_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_TEMA VARCHAR (60) NOT NULL UNIQUE,
    PRIMARY KEY (ID_TEMA)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ITEM_TEMA (
    ID_ITEM_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_ITEM_TEMA VARCHAR (60) NOT NULL,
    ID_TEMA INT NOT NULL,
    PRIMARY KEY (ID_ITEM_TEMA),
    FOREIGN KEY (ID_TEMA) REFERENCES TB_TEMA (ID_TEMA)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_COMENTARIO_USUARIO (
	ID_COMENTARIO_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    DATA_COMENTARIO_USUARIO DATETIME NOT NULL,
    TEXTO_COMENTARIO_USUARIO TEXT NOT NULL,
    RESPONDER_COMENTARIO_USUARIO INT,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_COMENTARIO_USUARIO),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_PROGRESSO_TEMA (
	ID_PROGRESSO_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    CONCLUIDO_PROGRESSO_TEMA TINYINT NOT NULL,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PROGRESSO_TEMA),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
