DROP DATABASE IF EXISTS DB_ENSINA_DEV;
CREATE DATABASE DB_ENSINA_DEV;
USE DB_ENSINA_DEV;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_USUARIO VARCHAR (80) NOT NULL, #UNIQUE,
    SENHA_USUARIO VARCHAR (255) NOT NULL,
    NOME_USUARIO VARCHAR (20) NOT NULL UNIQUE,
    IMAGEM_USUARIO VARCHAR (255) UNIQUE,	# caminho da imagem
    TIPO_USUARIO CHAR (1) NOT NULL,		# A = adm; E = estudante
    PRIMARY KEY (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'adm1', 'foto1.jpg', 'A');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est1', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est2', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est3', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est4', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est5', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est6', NULL, 'E');
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 1, 'est7', NULL, 'E');

CREATE TABLE TB_CONTATO (
	ID_CONTATO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_CONTATO VARCHAR(80) NOT NULL,
    TEXTO_CONTATO TEXT NOT NULL,
    DATA_CONTATO DATETIME NOT NULL,
    RESPONDIDO_CONTATO TINYINT NOT NULL,
    PRIMARY KEY (ID_CONTATO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);
INSERT INTO TB_CONTATO VALUES (DEFAULT, 'ensina.dev2022@gmail.com', 'Mensagem contato', NOW(), 0);

CREATE TABLE TB_TEMA (
    ID_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_TEMA VARCHAR (60) NOT NULL UNIQUE,
    PRIMARY KEY (ID_TEMA)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
INSERT INTO TB_TEMA VALUES (DEFAULT, 'HTML');
INSERT INTO TB_TEMA VALUES (DEFAULT, 'CSS');
INSERT INTO TB_TEMA VALUES (DEFAULT, 'JavaScript');
INSERT INTO TB_TEMA VALUES (DEFAULT, 'PHP');

CREATE TABLE TB_ITEM_TEMA (
    ID_ITEM_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_ITEM_TEMA VARCHAR (60) NOT NULL,
    ID_TEMA INT NOT NULL,
    PRIMARY KEY (ID_ITEM_TEMA),
    FOREIGN KEY (ID_TEMA) REFERENCES TB_TEMA (ID_TEMA)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
# HTML
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Basico', 1);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'TitulosParagrafoQuebraDeLinhaEImagens', 1);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Comentarios', 1);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'IdClassesNome', 1);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Form', 1);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Semantica', 1);
# CSS
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Basico', 2);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Comentarios', 2);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'OndeFicaOCss', 2);
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Cascata', 2);
# JavaScript
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'TiposVariaveisEscopos', 3);
# PHP
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Funcoes', 4);

CREATE TABLE TB_COMENTARIO_USUARIO (
	ID_COMENTARIO_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    DATA_COMENTARIO_USUARIO DATETIME NOT NULL,
    TEXTO_COMENTARIO_USUARIO TEXT NOT NULL,
    # no caso do comentário ser resposta, o id do original vem para cá
    RESPONDER_COMENTARIO_USUARIO INT,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_COMENTARIO_USUARIO),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
# adm1 html básico
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 1 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 2 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 3 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 4 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 5 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 6 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 7 usuário A', NULL, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 8 usuário A', NULL, 1, 1);
# est1 html? item2
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 1 usuário E', NULL, 2, 2);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 2 usuário E', NULL, 2, 2);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 3 usuário E', NULL, 2, 2);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 4 usuário E', NULL, 2, 2);
# est1 html? item3
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 2 usuário E', NULL, 2, 3);
# respostas adm1 para adm1 html básico
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 1 usuário A', 1, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 2 usuário A', 1, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 3 usuário A', 1, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 4 usuário A', 1, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 4 usuário A', 2, 1, 1);
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'resposta 5 usuário A', 3, 1, 1);

CREATE TABLE TB_PROGRESSO_TEMA (
	ID_PROGRESSO_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    CONCLUIDO_PROGRESSO_TEMA TINYINT NOT NULL,		# 0 ou 1
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PROGRESSO_TEMA),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_unicode_ci;
