SHOW DATABASES;

CREATE DATABASE DB_ENSINA_DEV;
USE DB_ENSINA_DEV;
SHOW TABLES;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_USUARIO VARCHAR (80) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR (255) NOT NULL,
    NOME_USUARIO VARCHAR (20) NOT NULL UNIQUE,
    IMAGEM_USUARIO VARCHAR (255) UNIQUE,	# caminho da imagem
    2FA_USUARIO TINYINT NOT NULL,	# adm sempre TRUE
    TIPO_USUARIO CHAR (1) NOT NULL,		# A = adm; C = cliente
    PRIMARY KEY (ID_USUARIO)
) ENGINE = INNODB;
DESCRIBE TB_USUARIO;
SELECT * FROM TB_USUARIO;

CREATE TABLE TB_PERGUNTA_FAQ (
	ID_PERGUNTA_FAQ INT NOT NULL UNIQUE AUTO_INCREMENT,
    TEXTO_PERGUNTA_FAQ TEXT NOT NULL,
    DATA_PERGUNTA_FAQ DATETIME NOT NULL,
    RESPONDIDO_PERGUNTA_FAQ TINYINT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PERGUNTA_FAQ),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB;
DESCRIBE TB_PERGUNTA_FAQ;
SELECT * FROM TB_PERGUNTA_FAQ;

CREATE TABLE TB_CONTATO (
	ID_CONTATO INT NOT NULL UNIQUE AUTO_INCREMENT,
    EMAIL_CONTATO VARCHAR(80) NOT NULL UNIQUE,
    TEXTO_CONTATO TEXT NOT NULL,
    DATA_CONTATO DATETIME NOT NULL,
    RESPONDIDO_CONTATO TINYINT NOT NULL,
    PRIMARY KEY (ID_CONTATO)
) ENGINE = INNODB;
DESCRIBE TB_CONTATO;
SELECT * FROM TB_CONTATO;

CREATE TABLE TB_TEMA (
    ID_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_TEMA VARCHAR (60) NOT NULL UNIQUE,
    DATA_TEMA DATETIME NOT NULL,
    PRIMARY KEY (ID_TEMA)
) ENGINE = INNODB;
DESCRIBE TB_TEMA;
SELECT * FROM TB_TEMA;
INSERT INTO TB_TEMA VALUES (DEFAULT, 'A', NOW());

CREATE TABLE TB_ITEM_TEMA (
    ID_ITEM_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOME_ITEM_TEMA VARCHAR (60) NOT NULL,
    DATA_ITEM_TEMA DATETIME NOT NULL,
    ID_TEMA INT NOT NULL,
    PRIMARY KEY (ID_ITEM_TEMA),
    FOREIGN KEY (ID_TEMA) REFERENCES TB_TEMA (ID_TEMA)
) ENGINE = INNODB;
DESCRIBE TB_ITEM_TEMA;
SELECT * FROM TB_ITEM_TEMA;
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'A', NOW(), 1);

CREATE TABLE TB_COMENTARIO_USUARIO (
	ID_COMENTARIO_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    DATA_COMENTARIO_USUARIO DATETIME NOT NULL,
    TEXTO_COMENTARIO_USUARIO TEXT NOT NULL,
    HISTORICO_COMENTARIO_USUARIO TEXT,
    RESPOSTA_COMENTARIO_USUARIO TEXT,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_COMENTARIO_USUARIO),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB;
DESCRIBE TB_COMENTARIO_USUARIO;
SELECT * FROM TB_COMENTARIO_USUARIO;

CREATE TABLE TB_PROGRESSO_TEMA (
	ID_PROGRESSO_TEMA INT NOT NULL UNIQUE AUTO_INCREMENT,
    PORCENTAGEM_PROGRESSO_TEMA INT,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PROGRESSO_TEMA),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB;
DESCRIBE TB_PROGRESSO_TEMA;
SELECT * FROM TB_PROGRESSO_TEMA;

UPDATE TB_USUARIO SET IMAGEM_USUARIO = 'foto1.jpg' WHERE ID_USUARIO = 1;
SELECT * FROM TB_COMENTARIO_USUARIO AS TBC JOIN TB_USUARIO AS TBU ON TBC.ID_USUARIO = TBU.ID_USUARIO WHERE TBC.ID_USUARIO = 1 ORDER BY TBC.DATA_COMENTARIO_USUARIO LIMIT 3;

SELECT TBP.PORCENTAGEM_PROGRESSO_TEMA, TBI.NOME_ITEM_TEMA
	FROM TB_PROGRESSO_TEMA AS TBP
    JOIN TB_ITEM_TEMA AS TBI
		ON TBI.ID_ITEM_TEMA = TBP.ID_PROGRESSO_TEMA
	WHERE ID_USUARIO = 2;
SELECT COUNT(ID_PROGRESSO_TEMA) AS 'EM PROGRESSO' FROM TB_PROGRESSO_TEMA WHERE ID_PROGRESSO_TEMA < 100 AND ID_USUARIO = 2;
SELECT COUNT(ID_PROGRESSO_TEMA) AS 'CONCLUÍDO' FROM TB_PROGRESSO_TEMA WHERE ID_PROGRESSO_TEMA = 100 AND ID_USUARIO = 2;

CREATE TABLE TB_FAVORITO_ITEM (
	ID_FAVORITO_ITEM INT NOT NULL UNIQUE AUTO_INCREMENT,
    SET_FAVORITO_ITEM TINYINT NOT NULL,
    ID_ITEM_TEMA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_FAVORITO_ITEM),
    FOREIGN KEY (ID_ITEM_TEMA) REFERENCES TB_ITEM_TEMA (ID_ITEM_TEMA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
) ENGINE = INNODB;
DESCRIBE TB_FAVORITO_ITEM;
SELECT * FROM TB_FAVORITO_ITEM;
