# inserindo tema
DESC TB_TEMA;
INSERT INTO TB_TEMA VALUES (DEFAULT, 'Título do tema', NOW());
SELECT * FROM TB_TEMA;

# inserindo item
DESC TB_ITEM_TEMA;
INSERT INTO TB_ITEM_TEMA VALUES (DEFAULT, 'Título do item', NOW(), 1);
SELECT * FROM TB_ITEM_TEMA;

# inserindo cliente
DESC TB_USUARIO;
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'usu', 1, 'nome cliente', NULL, 0, 'E');
SELECT * FROM TB_USUARIO WHERE TIPO_USUARIO = 'C';

# inserindo adm
DESC TB_USUARIO;
INSERT INTO TB_USUARIO VALUES (DEFAULT, 'adm', 2, 'nome adm', NULL, 1, 'A');
SELECT * FROM TB_USUARIO WHERE TIPO_USUARIO = 'A';

# inserindo comentário de usuário
DESC TB_COMENTARIO_USUARIO;
# no item 1
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 1 usuário', NULL, 0, 1, 1);
# no item 2 para ver se não pega a mais
INSERT INTO TB_COMENTARIO_USUARIO VALUE (DEFAULT, NOW(), 'comentário 2 usuário', NULL, 0, 2, 1);
SELECT * FROM TB_COMENTARIO_USUARIO;

# pegando da tabela intermediária
SELECT * FROM TB_COMENTARIO_ITEM
	JOIN TB_COMENTARIO_USUARIO
		ON TB_COMENTARIO_ITEM.ID_ITEM_TEMA = TB_COMENTARIO_USUARIO.ID_ITEM_TEMA
	ORDER BY TB_COMENTARIO_USUARIO.DATA_COMENTARIO_USUARIO;
